name: cd_workflow
on:
  push:
    branches:
      - develop
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    environment: "development-env"
    steps:
      - name: Welcome Step
        run: echo "App is GOing to be deployed on Render"
      - name: Send Alert to Render Using Callback URL
        run: curl -X POST ${{secrets.DEPLOY_HOOK_RENDER}}
      - name: Deployment Success
        run: echo "New Version of Web App Deployed on Render"